### ISSUE TITLE
Stress-testing / bulk sending transactions breaks shards on the testnet

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#2187]
**Describe the bug**
I made some changes to my stress-testing / bulk tx sending tool [harmony-tx-sender](https://github.com/SebastianJ/harmony-tx-sender) and briefly ran it on the testnet to make sure that the tool was working after my code changes.

After just running it for a brief moment it apparently broke shard 0 on the testnet.

**To Reproduce**

1. `mkdir -p harmony-tx-sender && cd harmony-tx-sender && bash <(curl -s -S -L https://raw.githubusercontent.com/SebastianJ/harmony-tx-sender/master/scripts/install.sh)`

2. Make sure that you have a funded account in your keystore

3. Use a max tx data size file for sending txs:
`cd data && rm -rf data.txt && curl -LOs https://gist.githubusercontent.com/SebastianJ/cdfc88c36f7687a3bfe9ef26c583c900/raw/516792ba7021ff9acfff4b63700f483c856a99d7/data.txt && cd ..`

4. Launch the tx sender:
`./harmony-tx-sender --network testnet --from YOUR_FUNDED_ACCOUNT_ADDRESS --count 100000 --pool-size 100 --from-shard 0 --to-shard 0`

**Expected behavior**
Shards should be able to withstand an increased amount of transactions and transactions with max data payloads.

**Comment by rlan35** [comment]
After investigation, we concluded that the cause is two fold:

1. The txns with large extra data overloaded the network and caused the leader to fail to send out Prepared messages.
2. View change got triggered, but the new leader sent our the newView msg with the Prepared multi-sigs. All nodes committed and the consensus is reached on the new block. The leader sent out the committed msg back to the nodes. However, since the originally Prepared msg which contains the raw block content was not sent successfully, the nodes are not able to accept the committed message. Thus the consensus stuck forever.

The solution is to resend the Prepared msg in the view change.

**Comment by LeoHChen** [comment]
I have recovered the testnet by rollback one block on the leader, and restart the shard0.  The testnet was recovered then.

**Comment by SebastianJ** [comment]
I implemented support for the staking network in my tx-sender and I needed to test it briefly on all shards on the staking testnet (os.hmny.io) to see verify that it could connect to each respective shard.

It could connect - so now all shards are broken / not in consensus 🤣

**Comment by fxfactorial** [comment]
@rlan35 Can we just reject transactions at the RPC/txn pool that have non-empty data field? That is, i thought that data field is only meaningful to smart contract

**Comment by AndyBoWu** [comment]
`
{"level":"info","port":"9000","ip":"54.86.8.44","length of newTxs":1,"totalPending":52,"totalQueued":128,"caller":"/home/ec2-user/harmony/node/node.go:287","time":"2020-02-09T03:22:35.401951417Z","message":"Got more transactions"}
{"level":"debug","port":"9000","ip":"54.86.8.44","caller":"/home/ec2-user/harmony/node/node_handler.go:108","time":"2020-02-09T03:22:35.402654151Z","message":"NET: received message: Node/Transaction"}
{"level":"warn","port":"9000","ip":"54.86.8.44","hash":"0x1e8c89ba388a0dbd2e0178faf4238394975bb03ac4132e12c4fd5aed82eb7417","from":"0x9c68e0de41d51c214bf292e74cb85b7d3adf3beb","to":"0xed1ebe4fd1f73f86388f231997859ca42c07da5d","caller":"/home/ec2-user/harmony/core/tx_pool.go:747","time":"2020-02-09T03:22:35.404818281Z","message":"Pooled new future transaction"}
{"level":"warn","port":"9000","ip":"54.86.8.44","hash":"0x1e8c89ba388a0dbd2e0178faf4238394975bb03ac4132e12c4fd5aed82eb7417","caller":"/home/ec2-user/harmony/core/tx_pool.go:1052","time":"2020-02-09T03:22:35.404863837Z","message":"Removed cap-exceeding queued transaction"}
`

**Comment by LeoHChen** [comment]
Recent launched a stress test network and a few nodes were down after load testing.  I found OOM from the nodes.

```
running: ./harmony -ip 18.236.69.198 -port 9000 -log_folder ../tmp_log/log-20200220.054238 -public_rpc -bootnodes /ip4/52.40.84.2/tcp/9845/p2p/QmbPVwrqWsTYXq1RxGWcxx9SWaTUCfoo1wA6wmdbduWe29,/ip4/54.86.126.90/tcp/9842/p2p/Qmdfjtk6hPoyrH1zVD9PEH4zfWLo38dP2mDvvKXfh3tnEv -min_peers 167 -blspass file:blsnopass.txt -blskey_file fb5c286f0ad78e1c029b874d96ee251c6761facf4279e95fe566af08221a1d05e1da580b9babe4f8a2f38ff0c5543c8f.key -delay_commit=2s -network_type=testnet -dns_zone=stn.hmny.io -public_rpc -dns_zone=stn.hmny.io
harmony is running, pid=3483
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x123abee, 0x16)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc07c000000, 0x4000000, 0x2176158)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x2153140, 0x8000, 0x7f83014acd01, 0x7f83a40ded28)
        /usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x2153140, 0x4, 0xffffffff)
        /usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x2153140, 0x4, 0x2176168, 0x7f8300fb0570)
        /usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x2153140, 0x4, 0xc007f80085, 0x7f8300fb0570)
        /usr/local/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1093 +0x4c
runtime.systemstack(0x7f8302ffcef0)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1146
```

**Comment by LeoHChen** [comment]
Logs of the recent STN network.

 s3://harmony-benchmark/logs/2020/02/20/054238

**Comment by SebastianJ** [comment]
Ok, so I activated pprof on the harmony node/binary in order to see what was hogging memory on the heap (suggested by the stack trace above).

This is before I started running the spammer on shard 0 and 1 on localnet:

- [Profile 1](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/profile001-no_spammers_active.pdf)

The following four profiles are the result of running the spammer on shard 0 and 1 on localnet (captured a few minutes a part - clearly showing how `pb (*Message) Unmarshal` just keeps accumulating more and more memory):

- [Profile 2 - 36.09 mb allocated](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/profile002-spammers_active.pdf)
- [Profile 3 - 69.10 mb allocated](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/profile003-spammers_active.pdf)
- [Profile 4 - 163.49 mb allocated](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/profile004-spammers_active.pdf)
- [Profile 5 - 252.22 mb allocated](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/profile005-spammers_active.pdf)

After these profiles I stopped the spammer, and the heap memory for `pb (*Message) Unmarshal` seems to get released:

- [Profile 6 - 155.77 mb allocated](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/profile006-spammer_stopped.pdf)
- [Profile 7 - 0.63 mb allocated](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/profile007-spam_stopped_later.pdf)

I haven't looked at the exact implementation detail of the p2p message unmarshalling - but one reason this is potentially happening could be that the entire message payload might be unmarshalled before the node decides on what to do with the message.

If this is the case, one potential solution is to send the sender address separately from the entire message JSON body/payload.

This way the node/tx pool can compare the address vs the pending queue/spam list and discard the message without even fully unmarshalling it (and thus preventing the memory allocation/potential OOP situation).

**Comment by SebastianJ** [comment]
Ok, so I ran pprof again (using a rebooted localnet), but this time without any tx payload whatsoever when spamming.

**Before running the spammers:**

- [Allocs report at the beginning](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/without-payload/allocs-beginning.pdf)
- [Heap profile 1 - before starting the spam](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/without-payload/profile001-no_spammers_active.pdf)

**While running the spammers:**

- [Heap profile 2](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/without-payload/profile002-spammers_running.pdf)
- [Heap profile 3](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/without-payload/profile003-spammers_running.pdf)
- [Heap profile 4](https://docs.google.com/viewer?url=http://tools.harmony.one.s3.amazonaws.com/pprof/without-payload/profile004-spammers_running.pdf)

**After stopping the spammers:**

- [Heap profile 5 - after stopping the spammers](profile005-no_spammers running.pdf)
- [Allocs profile before terminating localnet](allocs-end.pdf)

---

So it seems that it's the unmarshalling of the message payloads with large amounts of tx data attached that leads to a massive amount of memory getting allocated on the heap and eventually leading to nodes OOM-reaping.

**Comment by SebastianJ** [comment]
It's still possible to perform this attack - I broke consensus on shard 1-3 on the stressnet yesterday by using tx payload spam (shard 0 was already broken because of other stress tests).

**Comment by LeoHChen** [comment]
For stress test network, we shall at least one sentry node up as external nodes before we load test the network.  So that even though internal nodes are down, we can still keep the consensus going, more realistic network setup.

We need to re-visit the tx load spam issue in a more controlled network setup.

**Comment by stephen-tse** [comment]
@SebastianJ - @rlan35 @LeoHChen concluded punting this issue to fix before P3 launch but ok for stake heist (open hacking). rj/leo, can you add more context here? many p-ops are asking for context and expectations.

**Comment by LeoHChen** [comment]
@SebastianJ , totally understood your concern on the network security with the tx spam.  There were multiple issues that may cause this. Here is my summary and understanding of this issue and what we have done and could do.

1. network level tx spamming of invalid tx to end points caused multiple nodes down.  This has been fixed by @rlan35 's fix (https://github.com/harmony-one/harmony/pull/2308) to stop forwarding invalid tx to the entire network.
2. individual nodes were brought down by sending massive tx. This has been mitigated/fixed by @AndyBoWu 's security group update to whitelist rpc port to only trusted IPs instead of general public.
3. huge tx payload that may bring down individual node by OOM. This has been fixed by @Daniel-VDM 's fix (https://github.com/harmony-one/harmony/pull/2382) to drop the message if the size goes beyond the limit.
4. consensus stuck if massive valid tx were sent to the network that slowed down the entire network thus may lead to the loss of consensus. I believe this is still an open issue that we don't have a fix yet. However, the issue was reproduced in a test network w/o enough participation of external validators as internal voting power is capped to 68%. The mitigation is to setup at least one sentry external node per shard to make sure we have enough external voting power during the consensus if internal nodes were hit.

Really appreciate your detailed analysis and keen passion to set the high standard on the network security, which we should always keep especially on the blockchain network. Let me know if you still have more concerns.

I think we can do one more round of specific tx load spamming test on the stress testnet with a better setup so that we can confirm the fixes and understand the threshold of the issue, also to uncover potential other issues.

**Comment by SebastianJ** [comment]
This is still not fixed - I broke shard 1 on STN in a couple of minutes running tx payload spam with oversized tx data.

Nodes do not OOM now - but consensus still gets messed up.

**Comment by AndyBoWu** [comment]
"The txns with large extra data overloaded the network and caused the leader to fail to send out Prepared messages."

@SebastianJ what is the size of the extra data? 32 KB? We can set a rule to decline any request larger than certain size.

**Comment by SebastianJ** [comment]
@AndyBoWu Yes, there's a 32kb limit - and the nodes will invalidate txs above it.

What I did yesterday was actually sending valid txs (<32kb total tx size) and that crashed the shards. There has been some discussions about lowering the message body size, but that might lead to some incompatibility issues with the EVM implementation.

**Comment by SebastianJ** [comment]
Done additional tests today - round #1 @JB273 / @BrunoMarshall took down shard 0 & 1 (in less than 5 minutes total for both shards), round #2 @yelllowsin took down s0 in less than a minute and then shard 1 went down soon thereafter.

I've tried multiple iterations of this and the nodes can deal with invalid txs, but as soon as they have to process valid txs with a total size close to 32kb it seems they are kept busy to such a degree that consensus will stall and won't recover on its own (nodes are stuck in a perpetual view change).

**Comment by lijiang2087** [comment]
@fxfactorial: Also why shard 0 broke ? Because too much incoming spam causes a oom or the node just isn’t able to process messages fast enough and hence consensus stalls ?

@mindstyle85: Looks like 2nd option

**Comment by lijiang2087** [comment]
can we either close this or decide it's not a blocker for p2? @rlan35 @fxfactorial cc @Dewansahil @stephen-tse

**Comment by SebastianJ** [comment]
@lijiang2087 since Edgar's fixes it has been harder for me to crash STN - but P-OPS for example crashed it on Friday (and those nodes ran a version including Edgar's fixes).

Ideally this attack should be tested on both STN and OSTN with all of P-OPS at the same time/with full force, completely going all in and nuking both networks. If the networks can withstand that, yeah, I think we can close the issue.

But I don't see the point of closing this issue just because payload spam isn't included in the list of Stake Heist eligible bounties, it doesn't really make any sense.

**Comment by SebastianJ** [comment]
Closing this - after multiple tests after Edgar's fixes there have only been 2-3 distinctive stress runs with tx payloads that crashed the network, and one of them was during network initialization (JB spammed OSTN unknowingly while network was booting up).

Only OOM happening right now because of tx payload spam is the RPC/Explorer nodes crashing - but that's a separate (and identified) issue.

Will reopen the issue if tx payload stress tests manage to mess up consensus again during consecutive stress tests.
